<a href="https://colab.research.google.com/github/Sudipsamanta1/python-beginner/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy:


In [1]:
#creation of array:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [6]:
#Numpy
import numpy as np
array=np.array(my_list,dtype=int)
print(array)

print(type(array))

print(len(array))

print(array.ndim)

print(array.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
5
1
(5,)


In [11]:
array1=[1,2,3,4,5,6]
array2=array1.reshape(2,3)

print(array2.shape)
array2.shape

AttributeError: ignored

In [14]:
my_list2=[1,2,3,4,5]

my_list3=[2,3,6,5,8]

my_list4=[7,8,9,4,5]

mul_arr = np.array([my_list2,my_list3,my_list4])

print(mul_arr)

print(mul_arr.shape)


[[1 2 3 4 5]
 [2 3 6 5 8]
 [7 8 9 4 5]]
(3, 5)


In [18]:
#reshape mul in one

mul_arr.reshape(1,15)
mul_arr.reshape(5,3)


array([[1, 2, 3],
       [4, 5, 2],
       [3, 6, 5],
       [8, 7, 8],
       [9, 4, 5]])

# Numpy attributes

In [27]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a.shape)

#reshaping an array

a.shape=(4,2)
print(a)

b=a.reshape(2,4)
print(b)

(2, 4)
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[1 2 3 4]
 [6 7 8 9]]


In [29]:
r=range(24)
print(r)

a=np.arange(24)
print(a)
print(a.ndim)

range(0, 24)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [30]:
#reshaping the array a:

b=a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]
